config: Update yaml config file to the new standards
cycloid-community-catalog/infra-amazon-elk pull request #1
Opened 2018-02-05 10:04 UTC by Seraf

Cycloid platform is now able to have private stack, this update add some metadata on the public stack to let the backend be able to register them.

2018-02-05 10:48 UTC, gaelL approved these changes

2018-02-05 11:23 UTC, xescugc approved these changes

2018-02-06 13:38 UTC, xescugc requested changes

2018-02-06 13:38 UTC, XescuGC commented on .cycloid.yml
> +  - 'public'
Remove the `public`

2018-02-06 14:06 UTC, xescugc approved these changes

2018-02-06 14:06 UTC, merged